### ISSUE TITLE
Is it convenient to offer a Chinese mirror download url for the pre-trained model?

### ISSUE THREAD

**Issue by lukhy** [huggingface/pytorch-pretrained-BigGAN#4]
The downloading speed form amazonaws is not tolerant in China even for 200MB file.

**Comment by thomwolf** [comment]
It could be interesting but I'm not sure ho to handle the mirroring logic in the file caching utility.
Maybe just give alternate download links on the readme?

**Comment by lukhy** [comment]
I finally managed to download it by using proxy. I think this issue can be closed since it's commonly slow when downloading from foreign server.
